apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-deployment-s0
  name: redis-deployment-s0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod-s0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-pod-s0
    spec:
      containers:
        - image: redis:alpine
          name: redis-container
          command:
            - redis-server
            - "/redis-master-data/redis.conf"
            - "--sentinel"
          ports:
            - containerPort: 5004
          resources:
            requests:
              cpu: 1
          volumeMounts:
            - name: data
              mountPath: /redis-master-data
            - name: config
              mountPath: /redis-master
      initContainers:
        - name: copy
          image: busybox:latest
          command: [ 'sh', '-c', "cp /redis-master/redis.conf /redis-master-data/" ]
          volumeMounts:
            - name: data
              mountPath: /redis-master-data
            - name: config
              mountPath: /redis-master
      volumes:
        - name: config
          configMap:
            name: redis-sentinel-config-s0
            items:
              - key: redis-config
                path: redis.conf
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-s0
spec:
  ports:
    - nodePort: 30084
      port: 5004
      protocol: TCP
      targetPort: 5004
  selector:
    app: redis-pod-s0
  type: NodePort
