apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config-s0
data:
  redis-config: |
    port 5004
    sentinel monitor mymaster redis-service-master 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    sentinel announce-ip redis-service-s0
    sentinel announce-port 5004
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config-s1
data:
  redis-config: |
    port 5005
    sentinel monitor mymaster redis-service-master 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    sentinel announce-ip redis-service-s1
    sentinel announce-port 5005
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config-s2
data:
  redis-config: |
    port 5006
    sentinel monitor mymaster redis-service-master 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    sentinel announce-ip redis-service-s2
    sentinel announce-port 5006