apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-deployment-rep2
  name: redis-deployment-rep2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod-rep2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-pod-rep2
    spec:
      containers:
        - image: redis:alpine
          name: redis-container
          command:
            - redis-server
            - "/redis-master/redis.conf"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 1
          volumeMounts:
            - name: data
              mountPath: /redis-master-data
            - name: config
              mountPath: /redis-master
      volumes:
        - name: config
          configMap:
            name: redis-config-rep2
            items:
              - key: redis-config
                path: redis.conf
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-rep2
spec:
  ports:
    - nodePort: 30083
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-pod-rep2
  type: NodePort
